/**
 * Artist name to iTunes artistId.
 *
 * Why this exists: the Search API throttles hard — a burst of lookups can
 * leave an IP answering 403 for a long while, and six of the nine playlists
 * are built from artist searches. The lookup endpoint has no such problem, so
 * an artist whose id is known here is fetched with one unthrottled request
 * instead. Names not listed still fall back to search, which is why this file
 * can be filled in gradually rather than all at once.
 *
 * Generated by scripts/resolve-artist-ids.ts. Keys are matched
 * case-insensitively with punctuation and spaces removed.
 */
export const ARTIST_IDS: Record<string, number> = {
  "aespa": 1540251304,
  "Ariana Grande": 412778295,
  "Atom Chanakan": 958056826,
  "Big Ass": 7305579,
  "BIGBANG": 318754656,
  "BLACKPINK": 1141774019,
  "Bodyslam": 301727614,
  "Bowkylion": 1193225731,
  "fellow fellow": 599575151,
  "Ink Waruntorn": 1085511635,
  "Jennie": 913944,
  "Justin Bieber": 320569549,
  "Katy Perry": 64387566,
  "Kendrick Lamar": 368183298,
  "Loso": 1668996852,
  "MEYOU": 1335765508,
  "Michael Jackson": 32940,
  "Mirrr": 1444397487,
  "NCT 127": 1235849306,
  "Nont Tanont": 671377502,
  "Olivia Rodrigo": 979458609,
  "Palmy": 301261712,
  "Polycat": 253438210,
  "Pop Pongkool": 592702233,
  "Post Malone": 966309175,
  "Potato": 145027493,
  "PROXIE": 1618963162,
  "Season Five": 505368594,
  "Tattoo Colour": 286856254,
  "The Killers": 6483093,
  "Three Man Down": 1114898204,
  "Tilly Birds": 935689375,
  "Zeal": 93522843,
};
